version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile
    ports:
      - 80:8080
    restart: always
    tty: true
    volumes:
      - ./app/frontend/app:/app

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./app/backend/app:/app
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/backend/.env
    ports:
      - 5432:5432

volumes:
    postgres_data:
